[package]
name = "zpic-image"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true }
infer = { workspace = true }
image = { workspace = true, features = ["gif", "jpeg", "png", "webp", "bmp"] }
blake3 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
